### PR TITLE
Fix #3559: Component: Calendar -> keepInvalid no longer works

### LINKED ISSUE #3559: Component: Calendar
### Describe the bug

keepInvalid={true} property of Calendar no longer works

### Reproducer

https://stackblitz.com/edit/vitejs-vite-avhcdw?file=src/App.tsx

### PrimeReact version

8.7.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

Focus calendar, input anything from keyboard

### Expected behavior

Populate inputtext from calendar with keyboard values

### PR DESCRIPTION
**Pull request by cerbugabriel**
Defect fix for #3559.

### CODE REVIEW

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ export const Calendar = React.memo(
                 }
             } catch (err) {
                 //invalid date
-                const value = props.keepInvalid ? rawValue : null;
+                const value = props.keepInvalid ? event.value : null;
```
Comment (melloware) [inline components/lib/calendar/Calendar.js:121]: I actually think the line need to be this...

```js
const value = props.keepInvalid ? null : rawValue;
```

if you try your with `keepInvalid` it works but if you remove `keepInvalid` its allowing invalid characters

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/calendar/Calendar.js (hunk 1 above)
Comment (cerbugabriel) [reply components/lib/calendar/Calendar.js:121]: The difference between keepInvalid true and false should only be on onBlur. 
You can input invalid characters with it true and false, but, when inBlur state value remains on keepInvalid = true, and on keepInvalid = false makes the state value null.

Comment (melloware) [reply components/lib/calendar/Calendar.js:121]: Just try your fix above with both `keepInvalid={true}` and `keepInvalid={false}` you will see your fix does NOT work.  Then try mine you will see it does work.

Comment (cerbugabriel) [reply components/lib/calendar/Calendar.js]: I did a couple of digging and found out why it didn't update. updateInputField didn't work properly.

File: components/lib/calendar/Calendar.js [hunk 2]
```diff
@@ -1961,7 +1961,7 @@ export const Calendar = React.memo(
 
             let formattedValue = '';
 
-            if (value) {
+            if (value instanceof Date) {
```
Comment (melloware) [inline components/lib/calendar/Calendar.js:1964]: I don't think you can do this here because `issingleSelection` its a date but `isRangeSelection` and `isMultipleSelection` the value is not a DATE its an array of dates.

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by cerbugabriel — COMMENTED** [review]
Move condition for keepInvalid inside isSingleSelection.
(should only work for isSingleSelection)

File: components/lib/calendar/Calendar.js (hunk 2 above)
Comment (cerbugabriel) [reply components/lib/calendar/Calendar.js:1964]: You are right

**Review by cerbugabriel — COMMENTED** [review]
move props.keepInvalid to isSingleSelection

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Nice job!
