### PR TITLE
Fix(ColorPicker): apply s and b of previous hsb to hsbValue

### LINKED ISSUE #2808: MegaMenu: Start and End templates like MenuBar
### Describe the feature you would like to see added

Logo on MegaMenu similar to Menubar
Sometimes for creating menu with a lot of content MegaMenu is a much better solution
However for styling the menu its not possible to add the app logo at the start of the menu.

### LINKED ISSUE #6787: ColorPicker: the selected color is change to hug line color
### Describe the bug

when i change hug using hug line picker, the selected color is change to hug line color

https://github.com/primefaces/primereact/assets/37934668/7d28d84f-08fa-4c2e-9379-2997ead82aae

### Reproducer

https://primereact.org/colorpicker/#basic

### PrimeReact version

master

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

step 1. open color picker
step 2. change hug using hue handle of colorPicker -> the selected color is change to hug line color!

|step 1|step 2|
|---|---|
|스크린샷 2024-06-24 오전 9 12 44|스크린샷 2024-06-24 오전 9 12 47|

### Expected behavior

when hug line changed, the hug apply in selected color.

### PR DESCRIPTION
**Pull request by KumJungMin**
### Defect Fixes

- fix #6787 

<br/>

### modified list
1. `pageYOffset` is deprecated, So I changed `pageYOffset` to `scrollY` 
```js
// before
const top = hueViewRef.current.getBoundingClientRect().top + (window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0);
```
```js
// after
const top = hueViewRef.current.getBoundingClientRect().top + (window.scrollY || document.documentElement.scrollTop || document.body.scrollTop || 0);
```

<br/>

2. check undefined in Y position.
```js
const getPositionY = (event) => {
  if (event.pageY !== undefined) return event.pageY;
  else if (event.touches !== undefined) return event.touches[0].pageY;
  else return 0;
};
```

<br/>

3. **apply `s` and `b` of previous hsb to `this.hsbValue`**
```js
// before
hsbValue.current = validateHSB({
    h: Math.floor((360 * (150 - Math.max(0, Math.min(150, (event.pageY || event.changedTouches[0].pageY) - top)))) / 150),
    s: 100, // this!
    b: 100, // this!
});
```
```js
// after
hsbValue.current = validateHSB({
    h: hue,
    s: hsbValue.current.s, // changed code
    b: hsbValue.current.b // changed code
});
```

<br/>

### result

https://github.com/primefaces/primereact/assets/37934668/597c6ba5-d7d3-4c79-bf55-4f0fc8c53a1a

### CODE REVIEW

File: components/lib/colorpicker/ColorPicker.js [hunk 1]
```diff
@@ -97,13 +97,21 @@ export const ColorPicker = React.memo(
             !isUnstyled && DomHandler.addClass(elementRef.current, 'p-colorpicker-dragging');
         };
 
+        const getPositionY = (event) => {
+            if (event.pageY !== undefined) return event.pageY;
+            else if (event.touches !== undefined) return event.touches[0].pageY;
```
Comment (melloware) [inline components/lib/colorpicker/ColorPicker.js:102]: should this be `touches` or `changedTouches` ?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/colorpicker/ColorPicker.js (hunk 1 above)
Comment (KumJungMin) [reply components/lib/colorpicker/ColorPicker.js]: OOPS!! you're right 
thank you for comment :) ([63881b0](https://github.com/primefaces/primereact/pull/6788/commits/63881b09ff842091d4921d7d0747747b4ca58147))

**Review by melloware — APPROVED** [review]
