### PR TITLE
Fix #7074: ConfirmDialog - RejectButton classes in unstyled mode are not applied

### LINKED ISSUE #7074: ConfirmDialog: RejectButton classes in unstyled mode are not applied
### Describe the bug

Classes defined in pt are not applied in reject button.
Also, typescript type definitions for rejectButton and acceptButton are wrong.

### Reproducer

https://stackblitz.com/edit/aznirh?file=src%2Fmain.jsx

### System Information

- System:

    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 37.19 GB / 63.71 GB

-   Binaries:

    Node: 22.4.1 - ~\AppData\Local\nvs\default\node.EXE
    npm: 10.8.1 - ~\AppData\Local\nvs\default\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.CMD

-   Browsers:

    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527

-   npmPackages:

    react: 18.3.1 => 18.3.1

### Steps to reproduce the behavior

1. Go to reproducer
2. Inspect classes in reject button
3. Classes defined in pt are not applied

### Expected behavior

Classes defined in pt are passed and applied to reject button

### PR DESCRIPTION
**Pull request by ivanpajon**
### Defect Fixes
Fix #7074

### CODE REVIEW

File: components/lib/confirmdialog/ConfirmDialog.js [hunk 1]
```diff
@@ -154,18 +154,21 @@ export const ConfirmDialog = React.memo(
...
+                    className: classNames(getPropValue('rejectClassName'), cx('rejectButton', { getPropValue })),
+                    onClick: reject,
+                    pt: ptm('rejectButton'),
+                    unstyled: props.unstyled,
+                    __parentMetadata: {
+                        parent: metaData
+                    }
+                },
+                ptm('rejectButton')
+            );
```
Comment (melloware) [inline components/lib/confirmdialog/ConfirmDialog.js:172]: Do you need to do the same for acceptButton?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/confirmdialog/ConfirmDialog.js (hunk 1 above)
Comment (ivanpajon) [reply components/lib/confirmdialog/ConfirmDialog.js:172]: No I don't, because acceptButton already have mergeProps with ptm('acceptButton') and works fine.

**Review by melloware — APPROVED** [review]
