### PR TITLE
DataTable:converted to data- lookups instead of className lookups

### LINKED ISSUE #5489: DataTable: Resize "fit" doesnt work with unstyled
### Describe the bug

resizing doesnt work when resize mode is "fit" and unstyled is true

### Reproducer

https://stackblitz.com/edit/react-bghpmg?file=src%2FApp.js,src%2Findex.js

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Edge, Chrome

### Steps to reproduce the behavior

try to resize a column

### Expected behavior

_No response_

### LINKED ISSUE #5524: DataTable: need to be converted to data- lookups instead of className lookups
### Describe the bug

In unstyled mode,comp don't have classname,so need to be converted to data- lookups instead of className lookups

### Reproducer

_No response_

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by kl-nevermore**
Fix #5524 
Fix #5489

### CODE REVIEW

File: components/lib/datatable/DataTable.js [hunk 1]
```diff
@@ -557,7 +557,7 @@ export const DataTable = React.forwardRef((inProps, ref) => {
                     updateTableWidth(frozenBodyRef.current);
 
                     if (wrapperRef.current) {
-                        updateTableWidth(DomHandler.findSingle(wrapperRef.current, '.p-virtualscroller-content'));
+                        updateTableWidth(DomHandler.findSingle(wrapperRef.current, '[data-pc-name="virtualscroller"] > table > tbody'));
```
Comment (kl-nevermore) [inline components/lib/datatable/DataTable.js:560]: `[data-pc-name="virtualscroller"]  [data-pc-section="tbody"]` or add new data attr?

Comment (melloware) [reply components/lib/datatable/DataTable.js:560]: I think this is OK its saying find the first table and first tbody under `[data-pc-name="virtualscroller"]`

Comment (kl-nevermore) [reply components/lib/datatable/DataTable.js:560]: ok
