### PR TITLE
Fix #5863: Calendar enabledDates evaluated last

### LINKED ISSUE #5863: Calendar : enabledDates is not evaluated with disabledDays
### Describe the bug

When using ```disabledDays``` passing ```enabledDates``` is not working.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-cjy7lg?file=%2Fsrc%2Findex.js

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #5863: Calendar enabledDates evaluated last

### CODE REVIEW

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -2286,26 +2286,36 @@ export const Calendar = React.memo(
...
 
-            return false;
+            // last check for enabled dates to force dates enabled
+            if (props.enabledDates) {
+                console.log(props.enabledDates);
+
+                // possible re-enable already disabled date
+                if (props.enabledDates.some((d) => d.getFullYear() === year && d.getMonth() === month && d.getDate() === day)) {
+                    isDisabled = !isDisabled;
+                }
```
Comment (sdwillbrand) [inline components/lib/calendar/Calendar.js:2315]: If ```disabledDays``` and ```disabledDates``` is empty, this could disable the day. Since the first two if branches aren't entered, this negates the initial declaration.

File: components/lib/calendar/Calendar.js [hunk 2]
```diff
@@ -2286,26 +2286,36 @@ export const Calendar = React.memo(
...
                 if (props.disabledDays.indexOf(weekdayNumber) !== -1) {
-                    return true;
+                    isDisabled = true;
                 }
             }
 
-            return false;
+            // last check for enabled dates to force dates enabled
+            if (props.enabledDates) {
+                console.log(props.enabledDates);
```
Comment (sdwillbrand) [inline components/lib/calendar/Calendar.js:2310]: Is this intended?

Comment (melloware) [reply components/lib/calendar/Calendar.js]: Nope!

File: components/lib/calendar/Calendar.js (hunk 1 above)
Comment (melloware) [reply components/lib/calendar/Calendar.js:2313]: So I think that was the original design enabled Dates only enables dates so if you say "enabledDates" by itself those are the ONLY available dates enabled.  But in your scenario you want to re-enable dates that have been disabled.
