### PR TITLE
Fix #3092: Dropdown support required attribute

### LINKED ISSUE #3092: Dropdown: Required attribute doesn't work
### Describe the bug

After 8.X update the dropdown always count as unselected.

### Reproducer

https://codesandbox.io/s/crimson-field-vg9tzl?file=/src/DropdownDemo.js

### PrimeReact version

8.x.x

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Select an option
2. Click submit

### Expected behavior

Submit the form with the selected option

### PR DESCRIPTION
**Pull request by melloware**
###Defect Fixes
Fix #3092: Dropdown support required attribute

### CODE REVIEW

File: components/lib/dropdown/Dropdown.js [hunk 1]
```diff
@@ -600,11 +600,12 @@ export const Dropdown = React.memo(React.forwardRef((props, ref) => {
...
     const createHiddenSelect = () => {
         const placeHolderOption = <option value="">{props.placeholder}</option>;
-        const option = selectedOption ? <option value={selectedOption.value} selected>{getOptionLabel(selectedOption)}</option> : null;
+        let selectedValue = selectedOption ? getOptionValue(selectedOption) : "";
+        const option = selectedOption ? <option value={selectedValue}>{getOptionLabel(selectedOption)}</option> : null;
 
         return (
             <div className="p-hidden-accessible p-dropdown-hidden-select">
-                <select ref={inputRef} required={props.required} name={props.name} tabIndex={-1} aria-hidden="true">
+                <select ref={inputRef} required={props.required} value={selectedValue} name={props.name} tabIndex={-1} aria-hidden="true" onChange={(e) => selectedValue = e.target.value}>
```
Comment (mertsincan) [inline components/lib/dropdown/Dropdown.js:608]: @melloware did you try defaultValue instead of value and onChange?

Comment (melloware) [reply components/lib/dropdown/Dropdown.js:608]: Let me try again
