### PR TITLE
fix:InputNumber: Text selection not working on input focus when using a s…

### LINKED ISSUE #5537: InputNumber: Text selection not working on input focus when using a suffix or prefix
### Describe the bug

When rendering `<InputNumber>` with a prefix or suffix, tabbing to that input will not cause the text to be selected

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-662yfm

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 119

### Steps to reproduce the behavior

1. Open the forked codesandbox above
2. You'll see 3 inputs (the first without a prefix/suffix, and the other two with one)
3. Click on first input
4. Use tab / shift+tab to focus on the various inputs

### Expected behavior

Expected: When focused, the inputs have their text selected
Actual: Only the first input behaves this way. If there is a prefix or suffix, the text does not get selected

### PR DESCRIPTION
**Pull request by kl-nevermore**
Fix #5537

### CODE REVIEW

File: components/lib/inputnumber/InputNumber.js [hunk 1]
```diff
@@ -1067,6 +1078,7 @@ export const InputNumber = React.memo(
                     onKeyPress={onInputKeyUp}
                     onInput={onInput}
                     onClick={onInputClick}
+                    onMouseDown={onInputMouseDown}
```
Comment (melloware) [inline components/lib/inputnumber/InputNumber.js:1081]: Should this be `onPointerDown` instead so it works for touch devices as well?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/inputnumber/InputNumber.js (hunk 1 above)
Comment (kl-nevermore) [reply components/lib/inputnumber/InputNumber.js]: Thanks! I learned
