### PR TITLE
OverlayPanel fix following scroll

### LINKED ISSUE #7903: OverlayPanel: Position is not updated on scroll from wrapper element
### Describe the bug

If a part of your interface could scroll and displays an OverlayPanel: when scrolling, the overlay position is not updated.

https://github.com/user-attachments/assets/65bdffab-9f67-47f4-8cba-71ea54f828e1

Fix is coming in a PR:

https://github.com/user-attachments/assets/8921e5e1-2d5f-418d-a70d-fce08e5e066d

### Reproducer

_No response_

### System Information

```Shell
Primereact 10.9.3+
```

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by sescandell**
### Defect Fixes
Fix #7903

### CODE REVIEW

File: components/lib/utils/DomHandler.js [hunk 1]
```diff
@@ -647,10 +647,8 @@ export default class DomHandler {
              * @param {HTMLElement} node - Element to add
              */
             const addScrollableParent = (node) => {
-                if (hideOverlaysOnDocumentScrolling) {
-                    // For document/body/html elements, add window instead
-                    scrollableParents.push(node.nodeName === 'BODY' || node.nodeName === 'HTML' || node.nodeType === 9 ? window : node);
-                }
+                // For document/body/html elements, add window instead
+                scrollableParents.push(node.nodeName === 'BODY' || node.nodeName === 'HTML' || node.nodeType === 9 ? window : node);
```
Comment (melloware) [inline components/lib/utils/DomHandler.js:651]: This was intentional to only do it if hidedocumentonScrolling is set. Some users want the behavior and others don't depending on their accessibility needs for closing overlays.  So this is not the right fix

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by sescandell** [comment]
@melloware you were totally right!

The thing is, the scroll event from useOverlayListener is not really a scroll event because of how DomHandler.getScrollableParents is related to hideOnScroll. In the update of this PR, I changed this DomHandler.getScrollbaleParents behavior and adapted all components.

Before PR:

https://github.com/user-attachments/assets/2257ea51-dfae-45cb-9fc1-4383f277195f

After PR:

https://github.com/user-attachments/assets/e78270da-bfd8-4b8f-bbbc-2d6157d0e264

Let me know your thoughts. 

Thanks

File: components/lib/utils/DomHandler.js [hunk 2]
```diff
@@ -647,10 +646,8 @@ export default class DomHandler {
...
```
Comment (melloware) [inline components/lib/utils/DomHandler.js:650]: For readability i think we should add a `DomHandler.isDocumentNode(target)` method that does this `node.nodeType === 9` for readability. Then everywhere you use `node.nodeType === 9` change to use this new method which will make the code much more readable for eveyrone!

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/utils/DomHandler.js (hunk 2 above)
Comment (sescandell) [reply components/lib/utils/DomHandler.js:650]: Makes sense... commit is coming

**Review by melloware — APPROVED** [review]

**Comment by yabelozub** [comment]
After these changes, scrolling with open dropdown crashes with an error

Screenshot 2025-04-28 at 16 38 34
