### PR TITLE
Fix #7455: Decimal prevention in IntegerOnly and WithoutGrouping using numeric as reference in InputNumber

### LINKED ISSUE #7455: InputNumber: No possibility to prevent decimal values
### Describe the bug

As described [on the documentation](https://primereact.org/inputnumber/#numerals) page - there is a way to use the "Integer Only" and the "Without Grouping" options.

However, it's not working as expected on the demo page (the latest PrimeReact version) - when clicking on the "Edit in StackBlitz".
In the application I'm developing it's also not working,

Also, in the documentation, I don't see another way to handle the integer-only values.

### Reproducer

https://stackblitz.com/edit/cdfitb?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz 
    Memory: 13.17 GB / 31.93 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\NodeJS 20.10.0\node.EXE
    npm: 10.2.3 - C:\Program Files\NodeJS 20.10.0\npm.CMD   
  Browsers:
    Edge: Chromium (131.0.2903.51)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    primereact: ^10.8.4 => 10.8.4 
    react: ^18.2.0 => 18.2.0
```

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/cdfitb?file=src%2FApp.jsx
2. Type some decimal value, e.g `10.5` in the "Integer Only" or the "Without Grouping" field

### Expected behavior

The "Integer Only" and the "Without Grouping" options should work correctly, as in the Prime React documentation page

### PR DESCRIPTION
**Pull request by Sumeet-2023**
### Defect Fixes

Fixes #7455

### CODE REVIEW

File: components/lib/inputnumber/InputNumber.js [hunk 1]
```diff
@@ -709,8 +709,12 @@ export const InputNumber = React.memo(
                     newValueStr = insertText(inputValue, text, selectionStart, selectionEnd);
                     updateValue(event, newValueStr, text, 'insert');
                 } else if (decimalCharIndex === -1 && (maxFractionDigits || props.maxFractionDigits)) {
```
Comment (melloware) [inline components/lib/inputnumber/InputNumber.js:711]:
```suggestion
                } else if (decimalCharIndex === -1 && ((maxFractionDigits && maxFractionDigits > 0) || (props.maxFractionDigits && props.maxFractionDigits > 0))) {
```

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
OK tested your change looks good

**Comment by codalf** [comment]
Unfortunately, this fix breaks existing code and adds a new property `inputMode` which is not documented. Please revert.
With this change, decimal number are only posssble if the (undocumented) property 'inputMode' is set to something else than "numeric"

**Comment by Sumeet-2023** [comment]
@codalf Hey!
Could you please elaborate more on what existing code got broken so that i can make necessary changes if necessary :)
This pull request that I created was made keeping in features that were requested in pull request #7233 and in issue #7455

**Comment by codalf** [comment]
Hi @Sumeet-2023,
Please have a look at the isseu https://github.com/primefaces/primereact/issues/7977
There, I have added a reproducer. Basically, the default behavior has changed from allowing decimal number to not allowing it.
As an example you can take e.g. https://primereact.org/inputnumber/#prefixsuffix and compare the behavior with 10.9.5 and before.
