### PR TITLE
fix: incorrect default value for minFractionDigits when set to null

### LINKED ISSUE #6761: InputNumber: Incorrect default value for minFractionDigits when set to null
### Describe the bug

When InputNumber is used with the minFractionDigits attributes explicitly set to null, the default value used by the control is 0.
https://primereact.org/inputnumber/#api.InputNumber.props.minFractionDigits

It is described in the documentation "the default for currency formatting is the number of minor unit digits provided by the ISO 4217 currency code list"

### Reproducer

https://stackblitz.com/edit/mwqeju?file=src%2FApp.jsx

### PrimeReact version

10.6.6

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Use an InputNumber component where the minFractionDigits and maxFractionDigits are explicitly set to null in currency mode.
2. Enter a value

Default value is 0 fractional digits

### Expected behavior

Default value should be 2 fractional digits in currency mode

### PR DESCRIPTION
**Pull request by navedqb**
Fixes #6761

### CODE REVIEW

File: components/lib/inputnumber/InputNumber.js [hunk 1]
```diff
@@ -58,8 +58,8 @@ export const InputNumber = React.memo(
                 currency: props.currency,
                 currencyDisplay: props.currencyDisplay,
                 useGrouping: props.useGrouping,
-                minimumFractionDigits: props.minFractionDigits,
-                maximumFractionDigits: props.maxFractionDigits,
+                minimumFractionDigits: props.minFractionDigits ?? undefined,
+                maximumFractionDigits: props.maxFractionDigits ?? undefined,
```
Comment (melloware) [inline components/lib/inputnumber/InputNumber.js:62]:
```suggestion
                minimumFractionDigits: props.minFractionDigits ?? undefined, // #6761
                maximumFractionDigits: props.maxFractionDigits ?? undefined, // #6761
```

**Review by melloware — APPROVED** [review]
