### PR TITLE
fix: strength meter popup does not close on escape

### LINKED ISSUE #5321: Password: Strength meter does not close on escape key press
### Describe the bug

Strength meter popup does not close on escape key press

### Reproducer

https://primereact.org/password/#meter

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://primereact.org/password/#meter
2.  Enter a password.
3. Press escape once strength meter opens.

### Expected behavior

Strength meter popup should close on escape key press.

### PR DESCRIPTION
**Pull request by navedqb**
Fixes #5321

### CODE REVIEW

File: components/lib/password/Password.js [hunk 1]
```diff
@@ -201,7 +205,7 @@ export const Password = React.memo(
                 setMeterState(meter);
                 setInfoTextState(label);
 
-                if (!!keyCode && !overlayVisibleState) {
+                if (!!keyCode && keyCode !== 27 && !overlayVisibleState) {
```
Comment (melloware) [inline components/lib/password/Password.js:208]:
```suggestion
                const keyCode = e.code;

                if (!!keyCode && keyCode !== 'Escape' && !overlayVisibleState) {
                    show();
                }
```

Comment (melloware) [reply components/lib/password/Password.js:208]: You can delete the line `let keyCode = e.keyCode || e.which;` also

**Review by melloware — APPROVED** [review]
