### PR TITLE
Fix #3190: Menubar mobile view hamburger menu

### LINKED ISSUE #3190: Menubar: hide menu if no items in model
### Describe the bug

If there is no item added for the menu, the hamburger menu icon continues to appear in mobile view.

### Reproducer

_No response_

### PrimeReact version

8.4.0

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

If there is no item, the hamburger menu should not appear.

### PR DESCRIPTION
**Pull request by gucal**
Hamburger menu not showing when item is absent.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

File: components/lib/menubar/Menubar.js [hunk 1]
```diff
@@ -78,6 +78,9 @@ export const Menubar = React.memo(
         };
 
         const createMenuButton = () => {
+            if (props.model.length < 1) {
```
Comment (melloware) [inline components/lib/menubar/Menubar.js:81]: I would do `if (props.model && props.model.length < 1)`

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]
