### PR TITLE
Fix #6737 Calendar month navigator

### LINKED ISSUE #6737: Month skipped in dropdown when last day of month is greater than last day of next month
### Describe the bug

Steps to Reproduce:
1. Go to [StackBlitz Project](https://stackblitz.com/edit/amxz3a-p8vor8?file=src%2FApp.jsx).
2. Select "June" from the dropdown.

Expected Behavior:
The calendar should display the month of June.

Actual Behavior:
The calendar skips to July when June is selected.

Affected Versions:
Found in version 6.6.0
Reproduced in version 10.6.6

Request:
Please fix this issue for both affected versions.

### Reproducer

https://stackblitz.com/edit/amxz3a-p8vor8?file=src%2FApp.jsx

### PrimeReact version

10.6.6 and 6.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 125

### Steps to reproduce the behavior

1. Go to [StackBlitz Project](https://stackblitz.com/edit/amxz3a-p8vor8?file=src%2FApp.jsx).
2. Select "June" from the dropdown.
3. The calendar skips to July when June is selected.

### Expected behavior

The calendar should display the month of June.

### PR DESCRIPTION
**Pull request by KirilCycle**
### Defect Fixes
Fix #6737 Ensure the day of the date is reset before updating the calendar. The 'navBackward' and 'navForward' methods reset the date to the first day to prevent this bug. If the line 'newViewDate.setDate(1)' is removed, the same error observed with the options will occur.

### CODE REVIEW

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -480,6 +480,7 @@ export const Calendar = React.memo(
             const currentViewDate = getViewDate();
             let newViewDate = cloneDate(currentViewDate);
```
Comment (KirilCycle) [inline components/lib/calendar/Calendar.js:481]: Can i simply use new Date() ?

Comment (melloware) [reply components/lib/calendar/Calendar.js:481]: No this looks good if you look down in the calendar you will see we do this...

```js
currentDate.setDate(1); // #2948 always set to 1st of month
```

So clearly this spot was missed.

**Review by melloware — APPROVED** [review]
