### PR TITLE
Fix #6908: Missing props in MessagesPassThroughMethodOptions and MessagesProps

### LINKED ISSUE #6908: Messages: Missing props in MessagesPassThroughMethodOptions and MessagesProps
### Describe the bug

There are some missing props in type definition for Messages component.

### Reproducer

https://stackblitz.com/edit/2jqjp5?file=src%2FApp.tsx

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to reproducer
2. See linting error for unstyled prop (Error 1)
3. Open console
4. See object passed to MessagesPassThroughMethodOptions (Error 2)

### Expected behavior

Proper type definition for MessagesPassThroughMethodOptions and for Messages component unstyled prop.

### PR DESCRIPTION
**Pull request by ivanpajon**
### Defect Fixes
Fix #6908

### CODE REVIEW

File: components/lib/messages/messages.d.ts [hunk 1]
```diff
@@ -22,6 +22,9 @@ export declare type MessagesPassThroughTransitionType = ReactCSSTransitionProps
  */
 export interface MessagesPassThroughMethodOptions {
     props: MessagesProps;
+    state: MessagesState;
+    hostName?: string;
```
Comment (melloware) [inline components/lib/messages/messages.d.ts:26]: I will have to look. What is hostname?  Weird property for messages.

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/messages/messages.d.ts (hunk 1 above)
Comment (ivanpajon) [reply components/lib/messages/messages.d.ts:26]: Since last release I see that prop in some components... I don't know what it is neither. If you see my PR #6902 in the stackblitz reproducer, you will see that prop also for bodyRow in Datatable component.
I only include that prop here because it is passed through MessagesPassThroughMethodOptions.

**Review by melloware — APPROVED** [review]
