### PR TITLE
Fix #5283: InputText size TS fix

### LINKED ISSUE #5283: InputText inherits size from `HTMLInputElement` and size is number
### Describe the bug

```Comment
The HTMLInputElement interface provides special properties and methods for manipulating the options, layout, and presentation of <input> elements.
Supported by:
Chrome, Chrome Android, Edge, Firefox, Opera 8, Safari, Safari iOS
By Mozilla Contributors , CC BY-SA 2.5 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
***size: unsigned long:***
```

However, it is used by primereact as a string :

```javascript
{
 'text-lg px-4 py-4': props.size == 'large',
 'text-xs px-2 py-2': props.size == 'small',
 'p-3 text-base': props.size == null
}
```` 

### Reproducer

_No response_

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to https://primereact.org/inputtext/
2. Under tab theming 

### Expected behavior

From my POV this seems a violation of the Solid principle of ` Liskov Substitution Principle` or `Composition over inheritance`.

### PR DESCRIPTION
**Pull request by melloware**
Fix #5283: InputText size TS fix

### CODE REVIEW

File: components/lib/inputtext/inputtext.d.ts [hunk 1]
```diff
@@ -66,11 +66,15 @@ export interface InputTextContext {
...
-export interface InputTextProps extends Omit<React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>, 'onInput' | 'ref' | 'value'> {
+export interface InputTextProps extends Omit<React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>, 'onInput' | 'ref' | 'value' | 'size'> {
     /**
      * Format definition of the keys to block.
      */
     keyfilter?: KeyFilterType;
+    /**
+     * Size of the input.
+     */
+    size?: number | string | undefined;
```
Comment (Dalorzo) [inline components/lib/inputtext/inputtext.d.ts:77]: My only concern about allowing string is the `Liskov Substitution Principle`. Although, short term I agree it solves the problem.

**Review by Dalorzo — APPROVED** [review]
