### PR TITLE
Fix #7354: InputMask Classname p-filled not works fine

### LINKED ISSUE #7354: InputMask: Value not propagated
### Describe the bug

Value of inputmask is not propagated to inputtext component.
And if you set a value in inputmask and then disable/enable it, classname 'p-filled' is not set properly, causing float label working bad.

### Reproducer

https://stackblitz.com/edit/joufix?file=src%2FApp.tsx

### System Information

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 34.26 GB / 63.71 GB
  Binaries:
    Node: 22.4.1 - ~\AppData\Local\nvs\default\node.EXE
    npm: 10.8.1 - ~\AppData\Local\nvs\default\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    tailwindcss: 3.4.13 => 3.4.13
```

### Steps to reproduce the behavior

1. Go to reproducer
2. Toggle button "Click to see bug"

### Expected behavior

Classname 'p-filled' is properly set and float label should work fine.

### PR DESCRIPTION
**Pull request by ivanpajon**
### Defect Fixes
Fix #7354

### CODE REVIEW

File: components/lib/inputtext/InputText.js [hunk 1]
```diff
@@ -70,6 +70,14 @@ export const InputText = React.memo(
         const isFilled = React.useMemo(() => ObjectUtils.isNotEmpty(props.value) || ObjectUtils.isNotEmpty(props.defaultValue), [props.value, props.defaultValue]);
         const hasTooltip = ObjectUtils.isNotEmpty(props.tooltip);
 
+        React.useEffect(() => {
+            if (isFilled) {
+                DomHandler.addClass(elementRef.current, 'p-filled');
+            } else {
+                DomHandler.removeClass(elementRef.current, 'p-filled');
+            }
+        }, [props.disabled, isFilled]);
```
Comment (melloware) [inline components/lib/inputtext/InputText.js:79]: You use props.disabled here to trigger the hook but I don't see how that is used in the hook?

Comment (ivanpajon) [reply components/lib/inputtext/InputText.js:79]: props.disabled was included in useEffect dependencies because each time the component is enabled/disabled it needs to run that logic
