### PR TITLE
Fix: 6555 Missing PT Option for IconField in Password 

### LINKED ISSUE #6555: Missing PT Option for IconField in Password
### Describe the bug

Relates to #6349 - fixed by @melloware in #6493.
The point here is that I'm using `<Password>` within `display: flex`, and I'm no longer able to let the input grow. The reason is that there is no PT option within `<Password>` to give any `className` down to `IconField`.

[The relevant code can be found in password](https://github.com/primefaces/primereact/blob/7312fe466e189581c53c3fe43bf3381db4b59455/components/lib/password/Password.js#L483)

### Reproducer

https://primereact.org/password/#togglemask

### PrimeReact version

10.6.4

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by KirilCycle**
### Defect Fixes
Fix #6555 
IconField can be modified from Password component

### CODE REVIEW

File: components/lib/password/PasswordBase.js [hunk 1]
```diff
@@ -85,6 +85,7 @@ export const PasswordBase = ComponentBase.extend({
         header: null,
         content: null,
         footer: null,
+        iconField: null,
```
Comment (melloware) [inline components/lib/password/PasswordBase.js:88]: I don't think you need this we aren't adding a new property just a new passthrough.

File: components/lib/password/Password.js [hunk 2]
```diff
@@ -481,8 +481,18 @@ export const Password = React.memo(
         let input = <InputText {...inputTextProps} />;
 
         if (icon) {
+            const iconField = props.iconField;
```
Comment (melloware) [inline components/lib/password/Password.js:484]: I don't think you need the `iconField` part?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/password/PasswordBase.js (hunk 1 above)
Comment (KirilCycle) [reply components/lib/password/PasswordBase.js:88]: Without this it wont work 'React does not recognize the `iconField` prop on a DOM'

File: components/lib/password/Password.js (hunk 2 above)
Comment (KirilCycle) [reply components/lib/password/Password.js]: Well, I thought that in the future it would be easier to access the needed field value

File: components/lib/password/PasswordBase.js (hunk 1 above)
Comment (melloware) [reply components/lib/password/PasswordBase.js]: I just updated your PR can you do a git pull and test again with my changes?

File: components/lib/password/Password.js (hunk 2 above)
Comment (melloware) [reply components/lib/password/Password.js]: You can already change the icons with `props.hideIcon` etc.

```js
            if (unmaskedState) {
                icon = props.hideIcon || <EyeSlashIcon {...hideIconProps} />;
            } else {
                icon = props.showIcon || <EyeIcon {...showIconProps} />;
            }
```

File: components/lib/password/PasswordBase.js (hunk 1 above)
Comment (KirilCycle) [reply components/lib/password/PasswordBase.js]: Okey

**Comment by melloware** [comment]
I think these latest changes are good @nitrogenous !

**Review by melloware — APPROVED** [review]
