### PR TITLE
Fix #4181 -AvatarGroup: Avatar Hover tooltip

### LINKED ISSUE #4181: AvatarGroup -> Avatar Hover tooltip
### Describe the bug

When hovering the AvatarGroup - Avatar, the tooltip sets to 100% of the viewport, sometimes for a flash, other times it stays like that.

This is an image for what happened to me
Captura de ecrã 2023-03-24 094510

### Reproducer

https://stackblitz.com/edit/react-55hj5g-jskkgn?file=src%2Fdemo.js

### PrimeReact version

9.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

_No response_

### Steps to reproduce the behavior

Hover the avatars and the bug will flash sometimes and in other cases stay 

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by buraksaglam089**
Fix #4181 .

### CODE REVIEW

File: components/lib/tooltip/Tooltip.js [hunk 1]
```diff
@@ -150,7 +150,7 @@ export const Tooltip = React.memo(
                     elementRef.current.style.pointerEvents = 'none';
                 }
 
-                if ((isMouseTrack(currentTargetRef.current) || position == 'mouse') && !containerSize.current) {
+                if (((isMouseTrack(currentTargetRef.current) || position == 'mouse') && !containerSize.current) || (isMouseTrack(currentTargetRef.current) || position == 'mouse')) {
```
Comment (melloware) [inline components/lib/tooltip/Tooltip.js:153]: Since we are calling isMouseTrack method twice here break it out to a const on the line above.

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by habubey — APPROVED** [review]

**Review by melloware — APPROVED** [review]
