### PR TITLE
Fix #3139 : After resizing and reordering column takes the size of the column it is displacing

### LINKED ISSUE #3139: Column width not change after reorder in datatable
### Describe the bug

If I just modify column order it works fine: the column size goes with the modified column. But if i modify column order after i modified the column width, the column width doesn't go with the column, so that the column width don't change.

### Reproducer

https://codesandbox.io/s/datatable-reorder-vrlt9g

### PrimeReact version

8.3.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 103.0.5060.134, Firefox: 103.0.1, Microsoft Edge: 103.0.1264.77

### Steps to reproduce the behavior

orig columnWidths from the datatable session state: `columnWidths: "59,74,290,44,71"`
1. Modify a column width 
2. Modify the column order from position 3 to 2
new columnWidths from the datatable session state: `columnWidths: "59,74,290,44,71"`

### Expected behavior

If I modify column order from 3 to 2) after I modified a column width, the column widths change.
For example (with datatable session state):
orig `columnWidths: "59,74,290,44,71"`
new `columnWidths: "59,290,74,44,71"`

### PR DESCRIPTION
**Pull request by shuklabhisekh**
### Issues 
Fix #3139 - After resizing and reordering column takes the size of the column it is displacing  .

### CODE REVIEW

**Comment by shuklabhisekh** [comment]
Hey, @mertsincan, could you please review this Pull Request and please let me know if you've any feedback for this Pull Request?

**Comment by shuklabhisekh** [comment]
Hey @melloware, could you please review this PR and let me know if you have any feedback for me.

File: components/lib/datatable/DataTable.js [hunk 1]
```diff
@@ -714,6 +716,36 @@ export const DataTable = React.forwardRef((inProps, ref) => {
...
+                    ...remainingItems.slice(0, dropColIndex),
+                    movedItem,
+                    ...remainingItems.slice(dropColIndex)
+                ];
+                let innerHTML = '';
+
+                destroyStyleElement();
+                createStyleElement();
+
+                reorderedWidths.forEach((width, index) => {
```
Comment (melloware) [inline components/lib/datatable/DataTable.js:736]: I feel like this could be refactored into a method since it looks like `restoreColumnWidths` does almost the exact same thing?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/datatable/DataTable.js [hunk 2]
```diff
@@ -369,26 +369,30 @@ export const DataTable = React.forwardRef((inProps, ref) => {
...
             if (ObjectUtils.isNotEmpty(widths)) {
-                createStyleElement();
+                addInnerHtml(widths);
+            }
+        }
+    };
 
-                let innerHTML = '';
-                let selector = `.p-datatable[${attributeSelector.current}] > .p-datatable-wrapper ${isVirtualScrollerDisabled() ? '' : '> .p-virtualscroller'} > .p-datatable-table`;
+    const addInnerHtml = (widths) => {
```
Comment (melloware) [inline components/lib/datatable/DataTable.js:377]: Call it `addColumnWidthStyles`

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/datatable/DataTable.js (hunk 1 above)
Comment (shuklabhisekh) [reply components/lib/datatable/DataTable.js]: Hey @melloware, I've refactored the code as per your comment. Please review it.

File: components/lib/datatable/DataTable.js (hunk 2 above)
Comment (melloware) [reply components/lib/datatable/DataTable.js:377]: Also looks like there is LINT issue.

```
./components/lib/datatable/DataTable.js
730:17  Error: Expected blank line before this statement.  padding-line-between-statements
```

Comment (shuklabhisekh) [reply components/lib/datatable/DataTable.js]: Hey @melloware, calling it `addColumnWidthStyles` as per your comment and fixed lint issues.

**Review by melloware — APPROVED** [review]

**Review by melloware — APPROVED** [review]

**Comment by shuklabhisekh** [comment]
Hey @melloware, Thank you for approving this PR. Requesting you to please merge it also so that the bug can be fixed.

**Comment by melloware** [comment]
This now is looking so much better and cleaner!   I assigned to PrimeTek to review.

**Comment by shuklabhisekh** [comment]
Hey @habubey, could you please review this PR and let me know if you have any feedback for me

**Comment by habubey** [comment]
> Hey @habubey, could you please review this PR and let me know if you have any feedback for me

We will check and get back to you, We should ensure and test that the PR does not cause any issues or disrupt elsewhere in this component, as you know, the DataTable is a complex component.

**Comment by shuklabhisekh** [comment]
Hey @melloware, any update for this PR ?

**Comment by melloware** [comment]
@shuklabhisekh PrimeTek is reviewing it.  Trust me it will eventually get reviewed!

Also want to investigate this issue: https://github.com/primefaces/primereact/issues/4471 ???

**Comment by melloware** [comment]
@habubey multiple people on Discord also complaining about this issue it would be great if you could test and verify it?

**Review by melloware — APPROVED** [review]

**Comment by shuklabhisekh** [comment]
Hey @melloware, @mertsincan, @habubey  could you please provide me with an update on the status of this pull request? I would appreciate any information you can share. Thank you!

**Comment by melloware** [comment]
I will test this tomorrow.
