### PR TITLE
Fix #6791: apply year change in Calendar when input changed

### LINKED ISSUE #6781: Calendar: Manual Typing doesn't update the year on the top
### Describe the bug

When you want to input manually a date i.e. 11/12/2021, the month and day get changed, but the year on the top remains the same. It can be reproduced live on the first input calendar: https://primereact.org/calendar/

image

### Reproducer

https://stackblitz.com/run?file=src%2FApp.jsx

### PrimeReact version

10.6.6

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

1. Go To Calendar
2. Type 11/12/:anyYear

### Expected behavior

The Year on the top to also be changed in the visual menu

### LINKED ISSUE #6791: DataTable with Virtual Scroller and Multiselect; onSelectionChanged provides incorrect selections and [...undefined, undefined, ...]
### Describe the bug

This is sort of 2 problems, both related to the Shift+Click row selection.

1. Incorrect selections being provided onSelectionChange
    - Click selecting one row, followed by scrolling and shift+clicking another to select all elements between. In my example I select row 0 and shift+click row 150, which the onSelectionChange callback shows as selecting 151 total rows (correct) but with rows 80-231 instead of 0-150. See the video below.

https://github.com/primefaces/primereact/assets/64556428/c425b8c3-fb38-4b51-8d5e-f26feaf54cee

2. Selections provided onSelectionChange include numerous undefined rows. 
    - I am assuming this has something to do with the virtual scroller. Similar to the first issue described, I am selecting row, then scrolling down and shift+click selecting another. This often results in a number of the selected rows returned in the onSelectionChange callback being undefined. See the video below.

https://github.com/primefaces/primereact/assets/64556428/3467eb41-0f4f-45ac-b6e1-8315f34efa5c

I have also seen both of these issues happen together (I believe the second video shows this)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-to2pri?file=src%2FApp.jsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Click select a row (e.g. the row 0)

2. Scroll down a number of "pages" so the virtual scroller loads more data

3. Shift+Click to select up to and including another row (e.g. row 150)

4. Observe the console.log values and what is visually shown as being selected in the table

### Expected behavior

I would expect the onSelectionChanged callback to return an accurate list of selected rows, and not to have any rows undefined.

### PR DESCRIPTION
**Pull request by KumJungMin**
## Defect Fixes
- fix #6781

<br/>

### Related Issue and PR
- this issue is related this previous [PR](https://github.com/primefaces/primereact/pull/3517/files) and [issue 1](https://github.com/primefaces/primereact/issues/3515), [issue 2](https://github.com/primefaces/primereact/issues/3516).

_previous issue capture_

스크린샷 2024-06-26 오후 9 08 12

스크린샷 2024-06-26 오후 9 08 05

<br/>

_previous pr_
스크린샷 2024-06-26 오후 9 09 57

<br/><br/>

### how to resolve
- Whether the calendar picker is visible or not, the date should be updated.
- So, I deleted `!visible` condition in `useUpdateEffect` hook. :)

```js
// before
useUpdateEffect(() => {
	if (!visible && newDate) { ... } 
    ...
})
``` 
```js
// after
useUpdateEffect(() => {
	if (!newDate) return;
    ...
})
``` 

<br/>

### result
1. you can change date value using external button.(_previous issue_)

https://github.com/primefaces/primereact/assets/37934668/a68d34d3-6c1a-498b-8a46-b25bd59d2324

2. you can change date value using date input.

https://github.com/primefaces/primereact/assets/37934668/6fd4a77a-3b83-4ab1-854d-63d9576be2e8

### CODE REVIEW

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -3070,29 +3070,29 @@ export const Calendar = React.memo(
                 isTypingRef.current = false;
 
                 // #3516 view date not updated when value set programatically
-                if (!visible && newDate) {
```
Comment (melloware) [inline components/lib/calendar/Calendar.js:3073]: You remove the !visible check?

also did you retest ticket #3516 ?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/calendar/Calendar.js (hunk 1 above)
Comment (KumJungMin) [reply components/lib/calendar/Calendar.js:3073]: I deleted `!visible` condition and changed to early return :)
I checked the #3516 ticket, It works as shown in the video below



https://github.com/primefaces/primereact/assets/37934668/4178371a-3f4e-4b20-ac39-b59c5fd723b3

**Review by melloware — APPROVED** [review]
Nice!
