### PR TITLE
Fix #6795: Fix calendar overlay requiring double click on date to select a value when mask is present

### LINKED ISSUE #6795: Calendar Mask: Selecting a value from the dropdown is not triggered on first click
### Describe the bug

When you use a mask for the calendar and then click on a desired date in the same month, the first click does nothing, the second will accept the value change. Added a short video, but not sure if it showcases it clearly

https://github.com/primefaces/primereact/assets/142225925/facbf23d-dc59-4d26-837e-4495fbbe5d28

**NOTE**: Changing the month or the year, will make the click work as intended. Only when the month hasn't changed, the first click is disregarded

Could potentially be related to issue #6792

### Reproducer

https://stackblitz.com/edit/2baebw?file=src%2FApp.jsx

### PrimeReact version

10.6.6

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

1. Use Calendar Mask 
2. Select by click a value without changing month/year
3. Nothing happens
4. Select again
5. The value has been selected

---

1. Use Calendar Mask
2. Input manually a date
3. Select a date from the dropdown without changing month/year
4. The first click is disregarded
5. Select again
6. The value has been selected

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by frle10**
Fix #6795: Fix calendar overlay requiring double click on date to select a value when mask is present

### CODE REVIEW

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -3046,8 +3046,10 @@ export const Calendar = React.memo(
         }, [props.view]);
 
         useUpdateEffect(() => {
-            focusToFirstCell();
-        }, [currentView]);
+            if (visible) {
```
Comment (melloware) [inline components/lib/calendar/Calendar.js:3049]:
```suggestion
            if (visible && !props.inline) {
```

File: components/lib/calendar/Calendar.js [hunk 2]
```diff
@@ -3046,8 +3046,10 @@ export const Calendar = React.memo(
...
+                focusToFirstCell();
+            }
+        }, [visible, currentView]);
```
Comment (melloware) [inline components/lib/calendar/Calendar.js:3052]:
```suggestion
        }, [visible, currentViewm, props.inline]);
```

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by melloware** [comment]
It should not try and focus when its inline. This was reportde on Discord as its forcing the page to scroll: https://discord.com/channels/787967399105134612/787968635414118421/1268572988920299573

**Comment by frle10** [comment]
@melloware Thanks, fixed!

**Review by melloware — APPROVED** [review]
