### PR TITLE
Fix #3515/#3516: Calendar fix controlled value change

### LINKED ISSUE #3515: Calendar: Value does not update on external change
### Describe the bug

Changing the date via external means, e.g. a button, does not result in an instant update of the value shown. Only on opening and closing the pop-out does the value update.

A definite regression of the latest changes made from 8.6.0->8.7.0.

### Reproducer

https://codesandbox.io/s/focused-cloud-3w73if?file=/src/demo/CalendarDemo.js

### PrimeReact version

8.7.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Click button labeled '2023-11-01'.
2. Header and state updates, calendar value shown does not.
3. Open and close popout to see update.

### Expected behavior

Value shown should instantly update, as in previous version (8.6.0).

### LINKED ISSUE #3516: Calendar: Inconsistent behaviour around viewDate and changed value.
### Describe the bug

Depending on the order of 

1. Programmatically setting the date
2. Opening the pop-out

Either the new date or the old date is shown.

### Reproducer

https://codesandbox.io/s/focused-cloud-3w73if?file=/src/demo/CalendarDemo.js:1442-1452

### PrimeReact version

8.6.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Open the popout. Observe page is for 'Oct 2022'.
2. Click button to change date to '2023-11-01'.
3. Reopen popout and and see page for 'Nov 2022' (Note: The year here is also incorrect! It correct if you click into the year selector however...)

Alternatively
1.  Immediately click button to change date to '2023-11-01'.
2. Open popout, see page is still 'Oct 2022'.

### Expected behavior

If have not opened out the popout previously then it should open at the value that the date is currently set to, not the one that was set when initialised.

Problem is relevant when a minDate has been set, as it then opens up at an invalid date. If using custom datePickers this is a poor experience.

### PR DESCRIPTION
**Pull request by melloware**
### Defect Fixes
Fix #3515: Calendar fix controlled value change

Fix #3516: Inconsistent behaviour around viewDate and changed value.

### CODE REVIEW

**Comment by melloware** [comment]
I am not sure why previously it cared whether the popup was visible or not?

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -2489,8 +2489,18 @@ export const Calendar = React.memo(
...
+            const newDate = props.value;
+
+            if (previousValue !== newDate) {
+                updateInputfield(newDate);
+
+                // #3516 view date not updated when value set programatically
+                if (!visible && newDate) {
+                    validateDate(newDate);
+                    setViewDateState(newDate);
+                    setCurrentMonth(newDate.getMonth());
```
Comment (yrios-cdd) [inline components/lib/calendar/Calendar.js:2501]: @melloware When the `selectionMode` property of the `Calendar` component is `range` the value of the `newDate` variable is an array and the function `getMonth()` is not available.

Comment (melloware) [reply components/lib/calendar/Calendar.js:2501]: is already fixed check master
