### PR TITLE
fix: display Today for maxDate as today, handling seconds edge case too

### LINKED ISSUE #7602: Today Button not visible for maxDate
### Describe the bug

Today Button is not visible for maxDate as new Date()
This issue is linked to Defect: https://github.com/primefaces/primereact/issues/7598
with fix added  by me not supporting edge case(for few seconds just before midnight - 0 hours)  - merged PR: https://github.com/primefaces/primereact/pull/7597

### Reproducer

_No response_

### System Information

```Shell
10.9.1
```

### Steps to reproduce the behavior

pass maxDate as new Date()

### Expected behavior

Today Button visible for edge cases too (seconds before midnight)

### PR DESCRIPTION
**Pull request by suhailk4**
### Defect Fixes
Fix https://github.com/primefaces/primereact/issues/7598
Fix #7602
Updated the code for already merged PR: https://github.com/primefaces/primereact/pull/7597

In the new PR it will handle edge case for time 23:59:55+ seconds  . 

Let's say if now Date() is executed at almost midnight and passed in prop (new Date()) is behind by few milliseconds/seconds then the fix ( https://github.com/primefaces/primereact/pull/7597) added by me will fail for this case.  I've added a buffer of 10 seconds in next PR that should be sufficient for today button to be visible even for this edge case.

When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -4229,15 +4229,19 @@ export const Calendar = React.memo(
             );
         };
 
-        const truncateToMinutes = (date) => {
-            return new Date(date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), date.getMinutes());
+        const isTodayHiddenForMaxDate = () => {
```
Comment (melloware) [inline components/lib/calendar/Calendar.js:4232]: How about this...

```js
const isPastMaxDateWithBuffer = (bufferInSeconds = 10) => {
    const now = new Date();
    const maxDate = props.maxDate;
    return maxDate < now && Math.abs((now.getTime() - maxDate.getTime()) / 1000) > bufferInSeconds;
};
```

Name is more clear and passes the buffer in as a param

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/calendar/Calendar.js (hunk 1 above)
Comment (suhailk4) [reply components/lib/calendar/Calendar.js:4232]: yes, this is more clear. Making changes now.

**Review by melloware — APPROVED** [review]
