### PR TITLE
Fix: #7817 (Autocomplete type issue)

### LINKED ISSUE #7817: AutoComplete: Select and Unselect events has any typed value
### Describe the bug

`AutoCompleteSelectEvent` (and `AutoCompleteUnselectEvent` in extension) has `value` attribute typed as explicit `any` instead of being inferred from AutoComplete's `value`.

Image

### Reproducer

_No response_

### System Information

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 8.54 GB / 31.91 GB
  Binaries:
    Node: 22.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.7.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 11.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (134.0.3124.83)
    Internet Explorer: 11.0.26100.1882
```

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by sarathkumarsasi**
Added inferred types for AutoCompleteSelectEvent (and AutoCompleteUnselectEvent in extension). 
Fix #7817

### CODE REVIEW

**Comment by sarathkumarsasi** [comment]
> I don't think this is correct? It still won't pick up what `props.value` is from what I can tell?

Yes, you were right. I need to add the generic type in the props also; I have fixed it. Can you verify now?

**Comment by melloware** [comment]
I still don't think this is correct...

**Comment by sarathkumarsasi** [comment]
> I still don't think this is correct...

I have added typing for the autocomplete suggestions, I guess this will fix the issue. If not, can you suggest any other approach?

**Comment by melloware** [comment]
right i see `value: any` shouldn't that be `value: T` ?

**Comment by sarathkumarsasi** [comment]
> value: any

Yeah, I will change it. I found a way to test the changes locally, I will push after testing it.

File: components/lib/autocomplete/autocomplete.d.ts [hunk 1]
```diff
@@ -38,31 +38,33 @@ export interface AutoCompletePassThroughMethodOptions {
...
+interface AutoCompleteSelectEvent<T = any> {
     /**
      * Browser event
      */
     originalEvent: React.SyntheticEvent;
     /**
      * Selected option value
      */
-    value: any;
+    value: T extends any[] ? T[number] : T;
```
Comment (melloware) [inline components/lib/autocomplete/autocomplete.d.ts:58]: i don't understand T[number] here?

Comment (sarathkumarsasi) [reply components/lib/autocomplete/autocomplete.d.ts:58]: T[number] is a way to query the type of the elements in T when T is an array or tuple.
It’s like saying: "If T is an array, give me the type of its elements; otherwise, I don’t care about this part because the condition failed."
T[number] represents the type of elements that can be accessed by indexing into T with a number. Essentially, it "extracts" the type of the array's elements.
