### PR TITLE
Fix #4275: DataTable onContextMenuSelectionChange

### LINKED ISSUE #4275: DataTable: onContextMenuSelectionChange type incorrect
### Describe the bug

When using TypeScript to assign a value to onContextMenuSelectionChange as, an error occurs due to the parameter defined in TableData datatable.d.ts not matching the actual data type.

image

TableBody.js
```
const onRowRightClick = (event) => {
            if (props.onContextMenu || props.onContextMenuSelectionChange) {
                DomHandler.clearSelection();

                if (props.onContextMenuSelectionChange) {
                    //this
                    props.onContextMenuSelectionChange({
                        originalEvent: event.originalEvent,
                        value: event.data
                    });
                }

                if (props.onContextMenu) {
                    props.onContextMenu({
                        originalEvent: event.originalEvent,
                        data: event.data
                    });
                }

                event.originalEvent.preventDefault();
            }
        };
```

but,

datatable.d.ts
```
onContextMenuSelectionChange?(event: DataTableSelectionChangeEvent<TValue>): void;

interface DataTableSelectionChangeEvent<TValue extends DataTableValueArray> {
    /**
     * Browser event.
     */
    originalEvent: React.SyntheticEvent;
    /**
     * Selection object.
     */
    value: DataTableSelection<TValue>;
    /**
     * Type of the selection.
     */
    type?: string;
    /**
     * Extra options.
     */
    [key: string]: any;
}
```

### Reproducer

_No response_

### PrimeReact version

9.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by hicucu**
Fix #4275

### CODE REVIEW

File: components/lib/datatable/datatable.d.ts [hunk 1]
```diff
@@ -279,7 +279,20 @@ interface DataTableDataSelectableEvent<TValue extends DataTableValueArray> {
...
- * @see {@link DataTableProps.onContextMenuSelectionChange}, {@link DataTableProps.onSelectionChange}
+ * @see {@link DataTableProps.onContextMenuSelectionChange}
+ * @event
+ */
+interface DataTableContextMenuSelectionChangeEvent {
+    originalEvent: React.SyntheticEvent;
+    /**
+     * Selected rows data.
+     */
+    value: any;
```
Comment (melloware) [inline components/lib/datatable/datatable.d.ts:290]:
```suggestion
    data: DataTableRowDataArray<TValue>;
```

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/datatable/datatable.d.ts [hunk 2]
```diff
@@ -279,7 +279,20 @@ interface DataTableDataSelectableEvent<TValue extends DataTableValueArray> {
...
- * @see {@link DataTableProps.onContextMenuSelectionChange}, {@link DataTableProps.onSelectionChange}
+ * @see {@link DataTableProps.onContextMenuSelectionChange}
+ * @event
+ */
+interface DataTableContextMenuSelectionChangeEvent {
+    originalEvent: React.SyntheticEvent;
+    /**
+     * Selected rows data.
+     */
+    value: DataTableValue;
```
Comment (melloware) [inline components/lib/datatable/datatable.d.ts:290]: I am still not sure this is correct if you look at other Events?

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by melloware** [comment]
I just modified your commit
