### PR TITLE
Fix/date picker value entering

### LINKED ISSUE #6099: Calendar: manual input value is wrongly corrected when typing
### Describe the bug

Using dateFormat="yy.mm.dd" type "2024.03." and next start typing "18" or something like that. After you type "1" the date is set to 2024.03.01 and makes typing "18" here impossible. 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-uz69pt?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Start typing in Calendar 2024.03.
2. Try to type 18 next
3. NOT OK - input is changed to 2024.03.01

### Expected behavior

Parsing the date should be done only if provided input matches the format, so if dd is at the end .1 should not become .01 automatically

### PR DESCRIPTION
**Pull request by KirilCycle**
Fix #6099
## Description
Now calendar can work with short date format like 2024.03.1, and on blur it will roll back to standard  date format '2024.03.01'. Similar to vueprime behaviour.

### CODE REVIEW

File: components/lib/calendar/Calendar.js [hunk 1]
```diff
@@ -2457,6 +2461,10 @@ export const Calendar = React.memo(
                 }
             }
 
+            if (inputRef.current.value.length === formattedValue.length - 1 && !formatAlways) {
```
Comment (KirilCycle) [inline components/lib/calendar/Calendar.js:2464]: This wont allow rewrite input value from 2024.04.1 to 2024.04.01

**Comment by melloware** [comment]
Nice appreciate you keeping your eye on how Primevue is doing it!

File: components/lib/calendar/Calendar.js [hunk 2]
```diff
@@ -144,9 +144,10 @@ export const Calendar = React.memo(
 
         const updateValueOnInput = (event, rawValue, invalidCallback) => {
             try {
-                const value = parseValueFromString(rawValue);
+                const value = parseValueFromString(props.timeOnly ? rawValue.replace('_','') : rawValue);
```
Comment (KirilCycle) [inline components/lib/calendar/Calendar.js:147]: I noticed that timeOnly without mask work fine, this will pass for example '12:1' and 'isValidSelection' wont accept this as valid time, but with mask prop value will have underline at empty cels '12:1_' which can be approved by 'isValidSelection'

Comment (KirilCycle) [reply components/lib/calendar/Calendar.js:147]: We can modify code for accepting date like 12:1, however i guess this will have complex logic

**Comment by KirilCycle** [comment]
> Nice appreciate you keeping your eye on how Primevue is doing it!

Thanks!

File: components/lib/calendar/Calendar.js (hunk 2 above)
Comment (melloware) [reply components/lib/calendar/Calendar.js:147]: Yes it gets quite tricky real fast :)

Comment (KirilCycle) [reply components/lib/calendar/Calendar.js:147]: Replacing underline better add to 'parseDateTime' directly, and invoke replace method only if mask is passed

**Comment by KirilCycle** [comment]
Let me look deeper

File: components/lib/calendar/Calendar.js [hunk 3]
```diff
@@ -24,6 +24,7 @@ export const Calendar = React.memo(
         const [overlayVisibleState, setOverlayVisibleState] = React.useState(false);
         const [viewDateState, setViewDateState] = React.useState(null);
         const [idState, setIdState] = React.useState(props.id);
+        const typeUpdate = React.useRef(null);
```
Comment (melloware) [inline components/lib/calendar/Calendar.js:27]:
```suggestion
        const isTypingRef = React.useRef(false);
```

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@KirilCycle can you also test these tickets with your fix.  It seems this has been reported many times.

https://github.com/primefaces/primereact/issues/3728

https://github.com/primefaces/primereact/issues/4134

https://github.com/primefaces/primereact/issues/5986

https://github.com/primefaces/primereact/issues/6380

Thanks!  Let me know if your fix addresses any of these so I can mark this PR accordingly

**Comment by KirilCycle** [comment]
> @KirilCycle can you also test these tickets with your fix. It seems this has been reported many times.
> 
> #3728
> 
> #4134
> 
> #5986
> 
> #6380
> 
> Thanks! Let me know if your fix addresses any of these so I can mark this PR accordingly

Hello! Yes ill take a look

**Review by nitrogenous — APPROVED** [review]
LGTM. Thanks for your contributions

**Comment by KirilCycle** [comment]
> LGTM. Thanks for your contributions

My God, my first contribution to a huge project, I'm so happy :)

**Comment by KirilCycle** [comment]
> > @KirilCycle can you also test these tickets with your fix. It seems this has been reported many times.
> > #3728
> > #4134
> > #5986
> > #6380
> > Thanks! Let me know if your fix addresses any of these so I can mark this PR accordingly
> 
> We will close those issues if they are related  🙏

#3728 does not appear witch changes
#4134 still exist
#5986 does not appear 
#6380 does not appear

**Comment by melloware** [comment]
Thanks I linked those other tickets to this PR and closed them also
