### PR TITLE
Fix #3744 : fix index type of AccordionEventParams: add number[]

### LINKED ISSUE #3744: Accordion: Typescript def for `index` incorrect
### Describe the bug

onTabCange's params ```index``` type is numeric only.
That's a problem when using TypeScript.

But when using multimode in accordion, the index type can be ```number[]```.

### Reproducer

https://codesandbox.io/s/staging-currying-n6qnqs?file=/src/demo/AccordionDemo.tsx

### PrimeReact version

8.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 108, firefox 107

### Steps to reproduce the behavior

1. using typescript and using multimode in accordion
2. onTabChange params use array ```index``` inner value

### Expected behavior

image

### PR DESCRIPTION
**Pull request by hicucu**
Fix #3744 : fix index type of AccordionEventParams: add number[]

### CODE REVIEW

File: components/lib/accordion/accordion.d.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ type AccordionActiveIndexType = number | number[] | undefined | null;
 
 interface AccordionEventParams {
     originalEvent: React.MouseEvent<HTMLElement>;
-    index: number;
+    index: number | number[];
 }
```
Comment (melloware) [inline components/lib/accordion/accordion.d.ts:28]: the package-lock.json file should not have changed?

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by melloware** [comment]
Oh nevermind I see its just the 8.7.4-SNAPSHOT bump

**Review by melloware — APPROVED** [review]
