### PR TITLE
BodyRows merge rowClassName properly #5983

### LINKED ISSUE #5983: DataTable: rowClassName don't take prevalence over passthrough tailwind
### Describe the bug

The rowClassName attributes works and add the class `bg-primary` to row but the pt define some class `bg-white` that are applied after our customization.
We now have `bg-primary bg-white`

The step 4 of https://primereact.org/tailwind/#unstyledmode doesn't help (my twMerge is never called)

### Reproducer

https://stackblitz.com/edit/d8kwfr?file=src%2Fmain.jsx,src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

ALL

### Steps to reproduce the behavior

1. I took the exemple in https://primereact.org/datatable/#conditional_style
2. in main.jsx
```diff
+import Tailwind from 'primereact/passthrough/tailwind';
```

```diff
-    <PrimeReactProvider>
+    <PrimeReactProvider value={{ pt: Tailwind }}>
```

### Expected behavior

Class added with local customization should be visible instead of global classes.
My twMerge is used to resolve a conflict
I don't have to rewrite `bodyrow` to hide this bug. (this is my actual workaround)

### PR DESCRIPTION
**Pull request by Et7f3**
Fix #5983

Thanks for your quick reply and code indication @melloware,

[Even though it works](https://github.com/primefaces/primereact/issues/5983#issuecomment-1946902417)! I digged a bit and found the issue to happened elsewhere (the `mergeProps` function).

What is done in this PR:
- add the `classNameMergeFunction` props because `context.classNameMergeFunction` was undefined (and from docs it seems to be a left over of an old doc where it wasn't nested)
- re-order class by customisation: custom last so tailwind-merge works. I could keep the old line instead of `classNames(cx('bodyRow', { rowProps: props }), rowClassName)` but I think it could allow to override `bg-row-odd` but I am not sure.

This PR doesn't have test because I don't know how to write them (I am not a front end guy). I just tested by modifying the documentation example and see if it works.

before/after:
```diff
-bg-white text-gray-600 dark:bg-gray-900 transition duration-200 focus:outline focus:outline-[0.15rem] focus:outline-blue-200 focus:outline-offset-[-0.15rem] dark:text-white/80 dark:focus:outline dark:focus:outline-[0.15rem] dark:focus:outline-blue-300 dark:focus:outline-offset-[-0.15rem]`
+         text-gray-600 dark:bg-gray-900 transition duration-200 focus:outline focus:outline-[0.15rem] focus:outline-blue-200 focus:outline-offset-[-0.15rem] dark:text-white/80 dark:focus:outline dark:focus:outline-[0.15rem] dark:focus:outline-blue-300 dark:focus:outline-offset-[-0.15rem] bg-primary
```

PS: you know you can copy permalink so you can directly jumps to code
https://github.com/primefaces/primereact/blob/0083b8dea35159f6338e9cc003b4f991a067e555/components/lib/datatable/BodyRow.js#L471

### CODE REVIEW

File: components/lib/hooks/useMergeProps.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ export const useMergeProps = () => {
 
     return (...props) => {
         const options = {
-            ...(context?.ptOptions?.classNameMergeFunction && { classNameMergeFunction: context.classNameMergeFunction })
+            ...(context?.ptOptions?.classNameMergeFunction && { classNameMergeFunction: context.ptOptions.classNameMergeFunction })
```
Comment (melloware) [inline components/lib/hooks/useMergeProps.js:13]:
```suggestion
            ...(context?.ptOptions?.classNameMergeFunction)
```

Should it just be the above?  I am not sure what its appending classNameMergeFunction to itself again now?

File: components/lib/datatable/BodyRow.js [hunk 2]
```diff
@@ -465,10 +465,11 @@ export const BodyRow = React.memo((props) => {
     const content = createContent();
     const tabIndex = getTabIndex();
     const rowProps = mergeProps(
+        getBodyRowPTOptions('bodyRow'),
```
Comment (melloware) [inline components/lib/datatable/BodyRow.js:468]: Does this really need to be first now?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/datatable/BodyRow.js (hunk 2 above)
Comment (Et7f3) [reply components/lib/datatable/BodyRow.js:468]: It is needed because otherwise we have bg-primary before bg-white and tailwind merge keep last.

File: components/lib/hooks/useMergeProps.js (hunk 1 above)
Comment (Et7f3) [reply components/lib/hooks/useMergeProps.js:13]: Should be syntactically equivalent. Let me check.

File: components/lib/datatable/BodyRow.js (hunk 2 above)
Comment (Et7f3) [reply components/lib/datatable/BodyRow.js:468]: Or I can keep in second place and add rowClassName at third place so we minimise the change.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@EfrainTlapale this broke normal non-passthrough styling see #6194

**Comment by melloware** [comment]
Nevermind I see what broke it and it wasn't this change @Et7f3 !
