### PR TITLE
fix:Ripple and Tabview bugs in Next.js App Router

### LINKED ISSUE #5127: PrimeReactProvider: Error next14 app router
### Describe the bug

Captura de pantalla 2023-10-20 a la(s) 11 19 30
Captura de pantalla 2023-10-20 a la(s) 11 21 21
Captura de pantalla 2023-10-20 a la(s) 11 20 09
Captura de pantalla 2023-10-20 a la(s) 11 20 39

### Reproducer

_No response_

### PrimeReact version

10.0.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

chrome 118

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### LINKED ISSUE #5395: TabView: Doesn't render in NextJS 14
i'm using nextjs 14.0.3, prime react 10.1.1, i have follow walkthrough on your website but it seem not working for me, when i use tabview, tabpanel it return for me a blank div, what i have wrong, plz help me with this 

image

image

### PR DESCRIPTION
**Pull request by kl-nevermore**
Because I use Next14 in my project, So I fixed the forked project
Should we wait for PrimeTek to fix it or use a temporary solution first?

Fix #5395 

Fix #5127  refer to https://github.com/vercel/next.js/discussions/17443#discussioncomment-637879

### CODE REVIEW

File: components/lib/utils/ObjectUtils.js [hunk 1]
```diff
@@ -222,7 +222,13 @@ export default class ObjectUtils {
     static isValidChild(child, type, validTypes) {
         /* eslint-disable */
         if (child) {
-            const childType = this.getComponentProp(child, '__TYPE') || (child.type ? child.type.displayName : undefined);
+            let childType = this.getComponentProp(child, '__TYPE') || (child.type ? child.type.displayName : undefined);
+
+            // SSR next.js >= 13 (app router)
+            if (!childType && child?.type?._payload?.value) {
```
Comment (kl-nevermore) [inline components/lib/utils/ObjectUtils.js:228]: It might be better to refactor the component

Comment (melloware) [reply components/lib/utils/ObjectUtils.js:228]: I like this fix for now its the least intrusive

File: components/lib/ripple/Ripple.js [hunk 2]
```diff
@@ -77,13 +78,20 @@ export const Ripple = React.memo(
             getTarget: () => targetRef.current
         }));
 
-        useMountEffect(() => {
-            if (inkRef.current) {
+        useUpdateEffect(() => {
```
Comment (melloware) [inline components/lib/ripple/Ripple.js:81]: Should this just be `React.useEffect` and not update effect so it happens no matter what?  Right now its only happening on Update AFTER the component is mounted does this work in React.Strict and non-Strict mode?

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/ripple/Ripple.js (hunk 2 above)
Comment (kl-nevermore) [reply components/lib/ripple/Ripple.js:81]: I used to think that if context.ripple changes, Ripple will re-render 
But I just tested it and it won’t render [demo](https://codesandbox.io/p/sandbox/primereact-demo-forked-66cj8z?file=%2Fsrc%2Findex.js%3A14%2C17)
If this is the design, I think it can simplify like
```tsx
useEffect(()=>{
   setMounted(true);
},[])
 useUpdateEffect(() => {
            if ( isMounted && inkRef.current) {
                targetRef.current = getTarget();
                setDimensions();
                bindEvents();
            }
      
 }, [ isMounted]);
```

Comment (kl-nevermore) [reply components/lib/ripple/Ripple.js:81]: I haven't tested the production environment yet next12 13 14 and  vite

Comment (melloware) [reply components/lib/ripple/Ripple.js:81]: OK even simpler.

```js
useMountEffect(()=>{
   setMounted(true);
})
```

as that is exactly what useMountEffect does.

**Comment by kl-nevermore** [comment]
If use Next.js 13.x, we need to 
```tsx
import { PrimereactProvider } from 'primereact/api/api.esm'
import { Button } from 'primereact/button/button.esm'
...
```
Looks like a Next.js issue
I tested strictMode and non-strictMode in Next.js 14.x 12.x and vite project

**Comment by kl-nevermore** [comment]
I just test it working on 13.5.7-canary.37, But a new problem is coming

File: components/lib/utils/ObjectUtils.js [hunk 3]
```diff
@@ -222,7 +222,13 @@ export default class ObjectUtils {
...
+                childType = child.type._payload.value.find((v) => v === type);
```
Comment (kl-nevermore) [inline components/lib/utils/ObjectUtils.js:229]: There not compatible if you enable the experimental appDir in ~13.2

**Review by melloware — APPROVED** [review]
