### PR TITLE
Fix #5802: Allows clear filter button to render without filterMenu button

### LINKED ISSUE #5802: Datatable Column Filter: Clear Button will not show if filter menu button is hidden
### Describe the bug

In datatable, the clear filter button will now render unless filter button is also rendered

It appears that there may have been an erroneous change in this commit: https://github.com/primefaces/primereact/commit/deec2b2db26ebcfc98f56ba6b9cd2c31d6ac3b69 

### Reproducer

https://stackblitz.com/edit/vqsqhi?file=src%2FApp.jsx

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

Scroll down to the name column and see that showClearButton is set to true and showFilterMenu is false

### Expected behavior

If showClearButton is set to true and showFilterMenu is false, the clear button should still show

### PR DESCRIPTION
**Pull request by cassenhp**
Fix #5802

Fixes Issue where clear button will not be rendered if menu button is not rendered. In original issue fix listed below, I think that the check implemented in this issue was unintentionally placed in the createClearButton method

In reference to this issue:
https://github.com/primefaces/primereact/issues/4994

And this commit:
https://github.com/primefaces/primereact/commit/deec2b2db26ebcfc98f56ba6b9cd2c31d6ac3b69

### CODE REVIEW

File: components/lib/datatable/ColumnFilter.js [hunk 1]
```diff
@@ -563,10 +563,6 @@ export const ColumnFilter = React.memo((props) => {
     };
 
     const createClearButton = () => {
-        if (!showMenuButton()) {
```
Comment (melloware) [inline components/lib/datatable/ColumnFilter.js:566]: This should check !showClearButton which doesn't exist and needs to be created next to the showMenuButton.

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/datatable/ColumnFilter.js (hunk 1 above)
Comment (lbathp) [reply components/lib/datatable/ColumnFilter.js:566]: > This should check !showClearButton which doesn't exist and needs to be created next to the showMenuButton.

Doesn't [this line](https://github.com/primefaces/primereact/pull/5803/files/85a85ca43f303a67a5f91781c7aae86624602ec7#diff-b816aae7f5071fd81bcae0d885dbe0b2bbae790ce43618e2a26e2b52e6f076adR575) (line 579/575) already check if the clear button should be rendered or not?

Comment (melloware) [reply components/lib/datatable/ColumnFilter.js:566]: It does but its now not consistent with the MenuButton logic.  It should check it first and short circuit the whole method. Its cleaner and consistent. I am big on consistency!

Comment (melloware) [reply components/lib/datatable/ColumnFilter.js:566]: I can fix it if you don't have time.  Just let me know.

Comment (lbathp) [reply components/lib/datatable/ColumnFilter.js:566]: @melloware I know @cassenhp is sick and I do not have access to their fork - so that would be appreciated. Otherwise I can create my own fork and make the changes needed.

Comment (melloware) [reply components/lib/datatable/ColumnFilter.js:566]: @lbathp i will take care of it!  Thanks!
