### PR TITLE
MultiSelect: Allow to be inline on first render.

### LINKED ISSUE #7341: MultiSelect: inline can't be used at first render
### Describe the bug

I took the first example of documentation and I wasn't able to add `inline={true}`.

However if the component did render one time then their is no issue.

### Reproducer

https://stackblitz.com/edit/knzv8n?file=src%2FApp.jsx

### System Information

```Shell
N/A
```

### Steps to reproduce the behavior

1. Go on the link and see
2. Change default value of `displayed` to false and then it will show
3. Click the button to put to `true` and it won't have issue.

### Expected behavior

inline could be true when component is created.

### PR DESCRIPTION
**Pull request by Et7f3**
fix #7341 and #6838

### Defect Fixes
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

File: components/lib/multiselect/MultiSelect.js [hunk 1]
```diff
@@ -519,7 +519,7 @@ export const MultiSelect = React.memo(
         };
 
         const alignOverlay = () => {
-            DomHandler.alignOverlay(overlayRef.current, labelContainerRef.current.parentElement, props.appendTo || (context && context.appendTo) || PrimeReact.appendTo);
+            labelContainerRef.current && DomHandler.alignOverlay(overlayRef.current, labelContainerRef.current.parentElement, props.appendTo || (context && context.appendTo) || PrimeReact.appendTo);
```
Comment (melloware) [inline components/lib/multiselect/MultiSelect.js:522]:
```suggestion
            !props.inline && DomHandler.alignOverlay(overlayRef.current, labelContainerRef.current.parentElement, props.appendTo || (context && context.appendTo) || PrimeReact.appendTo);
```

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]

**Comment by Et7f3** [comment]
fix #6838

(it was not closed automatically)

So this repo doesn't want to participate in hacktoberfest ?

**Comment by melloware** [comment]
I would add the tag if I owned the repo but I can't!
