### PR TITLE
Fix #6949: Stepper: onChangeStep function not initially set

### LINKED ISSUE #6949: Stepper: onChangeStep function not initially set
### Describe the bug

The Stepper component does not initially have the onChangeStep function set which results in a warning message "Unknown event handler property `onChangeStep`. It will be ignored."

Once the component has rendered and changes are performed, the component works as normal.

### Reproducer

https://stackblitz.com/edit/8ur8c3?file=src%2FApp.jsx

### System Information

  System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-1370P
    Memory: 5.65 GB / 31.66 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    primereact: ^10.8.0 => 10.8.0
    react: ^18 => 18.2.0

### Steps to reproduce the behavior

1. Add the Stepper Component
2. Set the prop onChangeSet={(step) => console.log(step)}

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by meddvedev**
Fix #6949: Stepper: onChangeStep function not initially set

### CODE REVIEW

File: components/lib/stepper/StepperBase.js [hunk 1]
```diff
@@ -107,7 +107,8 @@ export const StepperBase = ComponentBase.extend({
         __TYPE: 'Stepper',
         activeStep: 0,
         orientation: 'horizontal',
-        linear: false
+        linear: false,
+        onChangeStep: undefined
```
Comment (melloware) [inline components/lib/stepper/StepperBase.js:111]:
```suggestion
        onChangeStep: null
```

We typically use NULL

**Review by melloware — CHANGES_REQUESTED** [review]

File: components/lib/stepper/StepperBase.js (hunk 1 above)
Comment (meddvedev) [reply components/lib/stepper/StepperBase.js]: Thank you for your comment, I'll keep it in mind

Comment (melloware) [reply components/lib/stepper/StepperBase.js]: Thanks for the PR.
